name: lint

on: [pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v1
      - uses: DoozyX/clang-format-lint-action@v0.5
        with:
          clangFormatVersion: 9

