name: macos

on:
  pull_request:
  push:
    branches:
      - master
      - 'release/**'

env:
  CORES: 2
  BUILD_MODE: normal
  GPG_VERSION: stable

jobs:
  tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11.0]
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 250
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup environment
        run: |
          . ci/gha/setup-env.inc.sh
      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ github.workflow }}-${{ matrix.os }}-${{ env.BUILD_MODE }}-gpg-${{ env.GPG_VERSION }}-${{ hashFiles('ci/**') }}-${{ hashFiles('.github/workflows/**') }}
      - name: Build cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          set -x
          ci/before_install.sh
          . ci/env.inc.sh
          ./ci/install.sh
      - name: tests
        run: ./ci/run.sh

