name: ubuntu

on:
  pull_request:
  push:
    branches:
      - master
      - 'release/**'

env:
  CORES: 2
  BUILD_MODE: normal
  GPG_VERSION: stable

jobs:
  tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup environment
        run: |
          . ci/gha/setup-env.inc.sh
      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ github.workflow }}-${{ runner.os }}-${{ env.BUILD_MODE }}-gpg-${{ env.GPG_VERSION }}-${{ hashFiles('ci/**') }}-${{ hashFiles('.github/workflows/**') }}
      - name: Build cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          set -x
          ci/before_install.sh
          . ci/env.inc.sh
          ./ci/install.sh
      - name: tests
        run: |
          set -x
          ./ci/run.sh
  cmake-offline-googletest:
    env:
      DOWNLOAD_GTEST: Off
      RNP_TESTS: rnp_tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup environment
        run: |
          . ci/gha/setup-env.inc.sh
      - name: Build
        run: |
          set -x
          ci/before_install.sh
          sudo apt-get -y install googletest
          mkdir -p "${LOCAL_BUILDS}/googletest-build"
          pushd "${LOCAL_BUILDS}/googletest-build"
          cmake /usr/src/googletest
          sudo make -j2 install
          popd
          . ci/env.inc.sh
          ./ci/install.sh
      - name: tests
        run: |
          set -x
          ./ci/run.sh
          [ -d "${LOCAL_BUILDS}/rnp-build/src/tests" ]
          [ ! -d "${LOCAL_BUILDS}/rnp-build/src/tests/googletest-build" ]
          [ ! -d "${LOCAL_BUILDS}/rnp-build/src/tests/googletest-src" ]
  cmake-disable-rubyrnp:
    env:
      DOWNLOAD_RUBYRNP: Off
      RNP_TESTS: rnp_tests.hash_test_success
      BUILD_SHARED_LIBS: yes
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup environment
        run: |
          . ci/gha/setup-env.inc.sh
      - name: Build
        run: |
          set -x
          ci/before_install.sh
          . ci/env.inc.sh
          ./ci/install.sh
      - name: tests
        run: |
          set -x
          ./ci/run.sh
          ls -la "${RNP_INSTALL}/lib/"librnp*.so
          ! ctest -N | grep 'ruby' > /dev/null
          ! ls -la src/tests/ | grep 'ruby' > /dev/null
