name: windows-msys2

on:
  pull_request:
  push:
    branches:
      - master
      - 'release/**'

env:
  BUILD_MODE: normal
  GPG_VERSION: stable
  CORES: 2

jobs:
  tests:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 70
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
      - name: install
        shell: msys2 {0}
        run: |
          bash ci/install_noncacheable_dependencies.sh
          bash ci/install_cacheable_dependencies.sh
      - name: tests
        shell: msys2 {0}
        run: bash ci/main.sh
      - shell: msys2 {0}
        run: |
          set -euxo pipefail
          wget https://github.com/lucasg/Dependencies/releases/download/v1.10/Dependencies_x64_Release.zip
          7z x Dependencies_x64_Release.zip
          ./Dependencies -exports $HOME/local-installs/rnp-install/bin/librnp*.dll > exports
          grep -qv dst_close exports
          grep -qw rnp_version_string exports
