name: windows

on:
  pull_request:
  push:
    branches:
      - master
      - 'release/**'

env:
  BUILD_MODE: normal
  GPG_VERSION: stable
  CORES: 2

jobs:
  tests:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 50
    steps:
      - name: Disable git eol translation
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: eine/setup-msys2@v1
        with:
          path-type: inherit
      - name: install
        shell: msys2 {0}
        run: bash ci/before_install.sh
      - name: tests
        shell: msys2 {0}
        run: bash -c ". ci/env.inc.sh && ci/main.sh"

